require("plugins.packer")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.lsp-colors")
require("plugins.transparent")
require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.telescope")
require("plugins.vimwiki")
require("plugins.context_filetypes")
require("plugins.alpha")
require("plugins.presence")
require("plugins.evil_lualine")

